In [ ]:
# Code to create a model used to predict whether the individual patient has an allergy
# Use different notebook to load the model and return a prediction

import os
os.environ["KERAS_BACKEND"] = "tensorflow"
import tensorflow
import keras

import numpy as np
np.random.seed(123)

In [2]:
import matplotlib
from keras.models import * 
from keras.layers import *
from keras.optimizers import RMSprop
import pandas as pd

# Import both datasets, change to local path when running
patients = pd.read_excel(r"C:\Users\me\OneDrive\Desktop\Senior Design\Allergy_SanFrancisco\PATIENTS_Nov_3_2023_V4_sfm-data.xlsx", sheet_name="Level2_AI_Patient Traits")

allergies = pd.read_excel(r"C:\Users\me\OneDrive\Desktop\Senior Design\Allergy_SanFrancisco\PATIENTS_Nov_3_2023_V4_sfm-data.xlsx", sheet_name="Level1_Patient Allergens")

In [3]:
# Confirm that patient sheet imported correctly
# Comment below line before committing
# patients['SkinConditions'].head()

In [4]:
# Confirm allergy sheet imported correctly
# Comment line before committing
# allergies.head()

In [5]:
# Merge columns by ID if needed
patientAllergies = patients.merge(allergies, on = "SFM Id")
# Comment line before committing
# patientAllergies.head()

In [6]:
# Drop ID and location columns from dataframe
patientsTrimmed = patients.drop(['SFM Id', 'City', 'State', 'Country'], axis = 1)

In [7]:
# One-hot encode Gender column
patientsTrimmed['Gender'] = pd.Categorical(patientsTrimmed['Gender'].str.strip())
gender_onehot = pd.get_dummies(patientsTrimmed['Gender'], prefix = "Gender",
                                    prefix_sep = "-", dtype = int)
patientsTrimmed = patientsTrimmed.drop('Gender', axis = 1)
patientsTrimmed = patientsTrimmed.join(gender_onehot)

In [8]:
# One-hot encode SkinTone column
patientsTrimmed['SkinTone'] = pd.Categorical(patientsTrimmed['SkinTone'].str.strip())
skintone_onehot = pd.get_dummies(patientsTrimmed['SkinTone'], prefix = "SkinTone",
                                    prefix_sep = "-", dtype = int)
patientsTrimmed = patientsTrimmed.drop('SkinTone', axis = 1)
patientsTrimmed = patientsTrimmed.join(skintone_onehot)

In [9]:
# One-hot encode FitzPatrickSkinPhotoType column
patientsTrimmed['FitzpatrickSkinPhotoType'] = pd.Categorical(patientsTrimmed['FitzpatrickSkinPhotoType'].str.strip())
# Dropping first here since it is a blank variable in the column
fitzpatrick_onehot = pd.get_dummies(patientsTrimmed['FitzpatrickSkinPhotoType'], prefix = "Fitzpatrick",
                                    prefix_sep = "-", drop_first = True, dtype = int)
patientsTrimmed = patientsTrimmed.drop('FitzpatrickSkinPhotoType', axis = 1)
patientsTrimmed = patientsTrimmed.join(fitzpatrick_onehot)

In [ ]:
# Switching to TextVectorization (Tokenizer is deprecated)
from keras.layers import TextVectorization
# Replace commas with whitespace
patientsTrimmed['SkinConditions'] = patientsTrimmed['SkinConditions'].str.replace(',', ' ')
# Set the max length based on whitespace characters
max_len = patientsTrimmed['SkinConditions'].str.count(' ').max()
# Create TextVectorization object, separating on whitespace and using the max_len from earlier
vectorizer = TextVectorization(split = 'whitespace', output_sequence_length = max_len)

In [ ]:
# Adapt using the column we want to convert
vectorizer.adapt(patientsTrimmed['SkinConditions'].values)
# Reset the column after converting values to vector and placing in array
skinConditions = vectorizer(patientsTrimmed['SkinConditions']).numpy()
patientsTrimmed = patientsTrimmed.drop('SkinConditions', axis = 1)

In [12]:
patientsArr = patientsTrimmed.values
input_data = np.concatenate((patientsArr, skinConditions), axis = 1)

In [ ]:
''' Old code for SkinConditions conversion - leaving in case we need later
# Code to preprocess the SkinConditions column, tokenizing should be more recognizable to keras than regular text
## Delete if this idea does not work
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences

# Flatten entries into actual lists
patientsTrimmed['SkinConditions'] = patientsTrimmed['SkinConditions'].apply(lambda x: ' '.join(x))
# Tokenize the characters of the columns
tokenizer = Tokenizer()
tokenizer.fit_on_texts(patientsTrimmed['SkinConditions'])
# Create and pad sequences of the tokens
patientsTrimmed['SkinConditions'] = tokenizer.texts_to_sequences(patientsTrimmed['SkinConditions'])
max_length = max(len(seq) for seq in patientsTrimmed['SkinConditions'])
testVar = pad_sequences(patientsTrimmed['SkinConditions'], maxlen = max_length, padding = "post")
patientsTrimmed['SkinConditions'] = testVar.tolist()
'''

In [14]:
# Drop ID column for preprocessing - ID should have no effect on prediction
allergiesNoId = allergies.drop('SFM Id', axis = 1)
# Remove all non-digit characters, then replace empty cells with NaN
allergiesNoId = allergiesNoId.replace(r'\D+', '', regex = True).replace('', np.nan)
# Set all NaN cells to 0
allergiesNoId = allergiesNoId.fillna(0)
# Convert entire dataframe to integer
allergiesNoId = allergiesNoId.astype(int)

In [15]:
allergiesNoId['AllergiesList'] = allergiesNoId.astype(str).apply(' '.join, axis=1)
allergiesNoId['AllergiesList'] = allergiesNoId['AllergiesList'].str.split()

In [16]:
from sklearn.preprocessing import MultiLabelBinarizer
# Create MultiLabelBinarizer object
mlb = MultiLabelBinarizer()

allergiesArr = np.array(allergiesNoId['AllergiesList'])
# Multi-hot encode data
allergiesArray = mlb.fit_transform(allergiesArr)

In [17]:
allergiesNew = mlb.inverse_transform(allergiesArray)

In [ ]:
allergiesDF = pd.DataFrame(mlb.transform(allergiesArr), columns = mlb.classes_)
allergiesDF.dtypes

In [81]:
from sklearn.model_selection import KFold
from sklearn.metrics import accuracy_score, multilabel_confusion_matrix
from keras.layers import Average

cv = KFold(n_splits=5, shuffle=True, random_state=7869)

fold_count = 1
# Train the model for each split
# Define the model inside the for loop
for train, test in cv.split(input_data,allergiesArray):

    n_classes = 731

    # Input layer
    input_shape = (40,)
    inputs = keras.Input(input_shape)

    # Hidden layers
    x = Dense(256, activation = 'sigmoid')(inputs)
    x = Dense(512, activation = 'sigmoid')(x)

    # Output layer - use multilabel classification
    predictions = Dense(n_classes, activation='sigmoid')(x)
    
    model = keras.Model(inputs = inputs, outputs = predictions)
    model.compile(loss=keras.losses.BinaryFocalCrossentropy(apply_class_balancing=True, alpha = 0.35, gamma = 14), optimizer=keras.optimizers.Adam(learning_rate=0.1))
    
    print("Running fold #: ", fold_count)

    fold_train_x =input_data[train]
    
    history = model.fit(
    fold_train_x, allergiesArray[train],
    epochs = 20, 
    verbose = 1, 
    validation_split=0.2
    )

    fold_test_x = input_data[test]
    y_true = allergiesArray[test]
    
    # pred_y = model.predict_classes(fold_test_x, verbose = 1)
    probs = model.predict(fold_test_x, verbose = 1)
    

    # AUC (Area Under Curve): how well the model can classify into the classes (high numbers better)
    auc = keras.metrics.AUC(multi_label = True, num_labels = 731, from_logits = False)
    # Precision: how well model predicts target class (high numbers better)\
    prec = keras.metrics.Precision()
    # Recall: how many objects model can find (high numbers better)
    rec = keras.metrics.Recall()
    # F1Score: mean between precision and recall
    f1 = keras.metrics.F1Score(average = 'weighted')

    threshold = 0.4
    probs = (probs > threshold).astype(int)
    # print("Predicted y values: ", pred_y[0])
    print("X values for test: ", fold_test_x[0])
    yList = mlb.inverse_transform(y_true)
    print("Actual y values as list: ", yList[0])
    probsList = mlb.inverse_transform(probs)
    print("Predicted values as list: ", probsList[0])
    print(probs[0])
    
    auc.update_state(y_true, probs)
    print(auc.result().numpy())
    prec.update_state(y_true, probs)
    print(prec.result().numpy())
    rec.update_state(y_true, probs)
    print(rec.result().numpy())
    f1.update_state(y_true, probs)
    print(f1.result().numpy())
    
    matrix = multilabel_confusion_matrix(y_true, probs)
    print(matrix)
    
    # print("Accuracy score sklearn: ", accuracy_score(allergiesArray[test], probs))
    accuracy = (allergiesArray[test] == probs).all(axis=(0,1)).mean()
    # print("Accuracy score equation: ", accuracy)

    fold_count = fold_count + 1

Running fold #:  1
Epoch 1/20
198/198 [==============================] - 2s 5ms/step - loss: 0.0171 - val_loss: 0.0084
Epoch 2/20
198/198 [==============================] - 1s 4ms/step - loss: 0.0056 - val_loss: 0.0060
Epoch 3/20
198/198 [==============================] - 1s 5ms/step - loss: 0.0042 - val_loss: 0.0054
Epoch 4/20
198/198 [==============================] - 1s 4ms/step - loss: 0.0038 - val_loss: 0.0044
Epoch 5/20
198/198 [==============================] - 1s 4ms/step - loss: 0.0028 - val_loss: 0.0036
Epoch 6/20
198/198 [==============================] - 1s 4ms/step - loss: 0.0032 - val_loss: 0.0040
Epoch 7/20
198/198 [==============================] - 1s 4ms/step - loss: 0.0031 - val_loss: 0.0041
Epoch 8/20
198/198 [==============================] - 1s 5ms/step - loss: 0.0026 - val_loss: 0.0025
Epoch 9/20
198/198 [==============================] - 1s 4ms/step - loss: 0.0022 - val_loss: 0.0024
Epoch 10/20
198/198 [==============================] - 1s 5ms/step - loss: 0.0019

0.3508892
0.035459306
0.9002417
0.24868229
[[[   0    0]
  [   0 1980]]

 [[1978    0]
  [   2    0]]

 [[1977    0]
  [   3    0]]

 ...

 [[1979    0]
  [   1    0]]

 [[1979    0]
  [   1    0]]

 [[1979    0]
  [   1    0]]]
Running fold #:  3
Epoch 1/20
198/198 [==============================] - 2s 5ms/step - loss: 0.0175 - val_loss: 0.0144
Epoch 2/20
198/198 [==============================] - 1s 4ms/step - loss: 0.0065 - val_loss: 0.0065
Epoch 3/20
198/198 [==============================] - 1s 4ms/step - loss: 0.0046 - val_loss: 0.0062
Epoch 4/20
198/198 [==============================] - 1s 4ms/step - loss: 0.0040 - val_loss: 0.0055
Epoch 5/20
198/198 [==============================] - 1s 4ms/step - loss: 0.0036 - val_loss: 0.0050
Epoch 6/20
198/198 [==============================] - 1s 4ms/step - loss: 0.0032 - val_loss: 0.0046
Epoch 7/20
198/198 [==============================] - 1s 4ms/step - loss: 0.0038 - val_loss: 0.0047
Epoch 8/20
198/198 [==============================] 

0.34336525
0.034323942
0.90796435
0.25001618
[[[   0    0]
  [   0 1979]]

 [[1979    0]
  [   0    0]]

 [[1977    0]
  [   2    0]]

 ...

 [[1976    0]
  [   3    0]]

 [[1979    0]
  [   0    0]]

 [[1979    0]
  [   0    0]]]
Running fold #:  5
Epoch 1/20
198/198 [==============================] - 2s 5ms/step - loss: 0.0111 - val_loss: 0.0098
Epoch 2/20
198/198 [==============================] - 1s 5ms/step - loss: 0.0047 - val_loss: 0.0051
Epoch 3/20
198/198 [==============================] - 1s 5ms/step - loss: 0.0031 - val_loss: 0.0041
Epoch 4/20
198/198 [==============================] - 1s 5ms/step - loss: 0.0023 - val_loss: 0.0038
Epoch 5/20
198/198 [==============================] - 1s 5ms/step - loss: 0.0028 - val_loss: 0.0039
Epoch 6/20
198/198 [==============================] - 1s 5ms/step - loss: 0.0020 - val_loss: 0.0030
Epoch 7/20
198/198 [==============================] - 1s 5ms/step - loss: 0.0020 - val_loss: 0.0028
Epoch 8/20
198/198 [==============================

In [ ]:
# TODO: Save Keras model as separate file